All formula updated to pass (most) strict auditing
- all formula updated to pass strict auditing
- Upgrade ots from 5.0.0 to 5.0.1
- Upgrade woff2 from 2015-07-13 to 2016-05-25
- some sha256 sums were wrong (my fault; do not curl GitHub download
  URLs for checksums
- repaired sfntly installation (moved to GitHub)
- added some basic tests to most formulas

Remaining unsolved audits:

- sfnt2woff, ttf2eot, and woff2 require tests:

	$ brew audit --strict --online sfnt2woff
	sfnt2woff:
	  * A `test do` test block should be added
	Error: 1 problem in 1 formula

	$ brew audit --strict --online ttf2eot.rb
	ttf2eot:
	  * A `test do` test block should be added
	Error: 1 problem in 1 formula

	$ brew audit --strict --online woff2.rb
	woff2:
	  * A `test do` test block should be added
	Error: 1 problem in 1 formula

- Not sure why this is happening (the website exists without any
  redirects required):

	$ brew audit --strict --online vfb2ufo.rb
	vfb2ufo:
	  * The homepage is not reachable (curl exit code 22)
	Error: 1 problem in 1 formula

- Some tests are really basic and low-quality and could use improvement
in the future.